### ISSUE TITLE
Build fails in MinGW64/MSYS2

### ISSUE THREAD

**Issue by oscarfv** [apnadkarni/twapi#24]
Hello Ashok. I'm the author of the feature request #137 on SF about source tarballs and MinGW support you just closed. Thank you very much!

After 11 yeas, you can figure out how much eager I was about trying this :-D so two minutes later I was following the build instructions.

On a MING64 MSYS2 shell (system updated a couple months ago, I see no relevant pending updates):

```
$ git clone https://github.com/apnadkarni/twapi.git
$ mkdir build && cd build
$ export TCLDIR=/mingw64
$  ../configure --enable-threads --enable-64bit --with-tcl=$TCLDIR/lib --with-tclinclude=$TCLDIR/include --prefix=$TCLDIR
$ make
gcc -DPACKAGE_NAME=\"twapi\" -DPACKAGE_TARNAME=\"twapi\" -DPACKAGE_VERSION=\"5.2.0\" -DPACKAGE_STRING=\"twapi\ 5.2.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_twapi=/\*\*/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DTcl_Size=int -DHAVE_SYSTEM_STATUS_FLAG=1 -DTCL_THREADS=1 -DUSE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DMODULE_SCOPE=extern -DHAVE_NO_SEH=1 -DHAVE_CAST_TO_UNION=1 -DHAVE_STDBOOL_H=1 -DTCL_WIDE_INT_TYPE=long\ long -DHAVE_STRUCT_STAT64=1 -DHAVE_OPEN64=1 -DHAVE_LSEEK64=1 -DHAVE_TYPE_OFF64_T=1 -DTCL_CFG_OPTIMIZED=1 -DUSE_TCL_STUBS=1 -DTCL_MAJOR_VERSION=8 -DUNICODE -D_UNICODE -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DPSAPI_VERSION=1 -DTWAPI_SINGLE_MODULE=1 -I. -I"D:/dev/other/twapi/twapi/include" -I"../dyncall/dyncall-0.9/include" -I"C:/apps/msys64/mingw64/include"    -pipe -O2 -fomit-frame-pointer -DNDEBUG -Wall   -c `cygpath -m ../win/calls.c` -o calls.o
In file included from D:/dev/other/twapi/win/calls.c:8:
D:/dev/other/twapi/win/calls.c: In function 'Twapi_CallObjCmd':
D:/dev/other/twapi/win/twapi.h:669:21: error: too many arguments to function 'Twapi_NewId'; expected 0, have 1
  669 | #define TWAPI_NEWID Twapi_NewId
      |                     ^~~~~~~~~~~
D:/dev/other/twapi/win/calls.c:1544:29: note: in expansion of macro 'TWAPI_NEWID'
 1544 |         result.value.wide = TWAPI_NEWID(ticP);
      |                             ^~~~~~~~~~~
D:/dev/other/twapi/win/twapi.h:1764:22: note: declared here
 1764 | TWAPI_EXTERN TwapiId Twapi_NewId();
      |                      ^~~~~~~~~~~
make: *** [Makefile:298: calls.o] Error 1
```

Executing `make -j 16` also shows errors in other files:

```
D:/home/twapi/win/ffi.c: In function 'ParseCStructHelper':
D:/home/twapi/win/ffi.c:303:34: error: assignment to 'TCL_RESULT (*)(void)' {aka 'int (*)(void)'} from incompatible pointer type 'TCL_RESULT (*)(Tcl_Interp *, Tcl_Obj *, int *)' {aka 'int (*)(Tcl_Interp *, Tcl_Obj *, int *)'} [-Wincompatible-pointer-types]
  303 |         case CSTRUCT_BOOLEAN: fn = ObjToBoolean; break;
      |                                  ^
In file included from D:/home/twapi/win/ffi.c:8:
D:/home/twapi/win/twapi.h:1512:25: note: 'ObjToBoolean' declared here
 1512 | TWAPI_EXTERN TCL_RESULT ObjToBoolean(Tcl_Interp *, Tcl_Obj *, int *);
      |                         ^~~~~~~~~~~~
D:/home/twapi/win/ffi.c:304:31: error: assignment to 'TCL_RESULT (*)(void)' {aka 'int (*)(void)'} from incompatible pointer type 'TCL_RESULT (*)(Tcl_Interp *, Tcl_Obj *, CHAR *)' {aka 'int (*)(Tcl_Interp *, Tcl_Obj *, char *)'} [-Wincompatible-pointer-types]
  304 |         case CSTRUCT_CHAR: fn = ObjToCHAR; break;
      |                               ^
D:/home/twapi/win/twapi.h:1552:25: note: 'ObjToCHAR' declared here
 1552 | TWAPI_EXTERN TCL_RESULT ObjToCHAR(Tcl_Interp *interp, Tcl_Obj *obj, CHAR *ucP);
      |                         ^~~~~~~~~
D:/home/twapi/win/ffi.c:305:32: error: assignment to 'TCL_RESULT (*)(void)' {aka 'int (*)(void)'} from incompatible pointer type 'TCL_RESULT (*)(Tcl_Interp *, Tcl_Obj *, UCHAR *)' {aka 'int (*)(Tcl_Interp *, Tcl_Obj *, unsigned char *)'} [-Wincompatible-pointer-types]
  305 |         case CSTRUCT_UCHAR: fn = ObjToUCHAR; break;
      |                                ^
D:/home/twapi/win/twapi.h:1551:25: note: 'ObjToUCHAR' declared here
 1551 | TWAPI_EXTERN TCL_RESULT ObjToUCHAR(Tcl_Interp *interp, Tcl_Obj *obj, UCHAR *ucP);
      |                         ^~~~~~~~~~
```

etc.

I hope to have time for investigating those issues soon but I'll like to know: what's the setup/environment you use to test the MinGW build? Also: did you try with CLANG64 MSYS2 environment?

twapi is a glaring omission on the MSYS2 package repository and I plan to add it ASAP.

Thanks again.

**Comment by apnadkarni** [comment]
These build errors should now be fixed. At least Github actions show no build errors with gcc 15.1 and I assume they use the latest, or very recent, msys distribution.

**Comment by oscarfv** [comment]
Hello again, Ashok. Thinks are progressing fast now :-)

The build works on MSYS2/MinGW-w64/gcc 64 bits.

The build also works on MSYS2/UCRT/clang 64 bits (this is the CLANG64 environment in MSYS2.)

On the Clang build this is shown:

```
$ ../configure --enable-64bit --enable-threads
...
configure: WARNING: 64bit support being disabled -- don't know magic for this platform
```

which seems unimportant, as there is no need to enable 64 bit mode on 64 bit MSYS2 toolsets.

And this warning, which looks legit to me:

```
2396:17: warning: variable 'pv2' is used uninitialized whenever '&&'
      condition is false [-Wsometimes-uninitialized]
 2396 |             if (ObjToLPVOID(interp, objv[1], &pv) != TCL_OK &&
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/dev/other/twapi/win/com.c:2400:73: note: uninitialized use occurs here
 2400 |             hr = ifc.recordinfo->lpVtbl->RecordCopy(ifc.recordinfo, pv, pv2);
      |                                                                         ^~~
D:/dev/other/twapi/win/com.c:2396:17: note: remove the '&&' if its condition is always true
 2396 |             if (ObjToLPVOID(interp, objv[1], &pv) != TCL_OK &&
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/dev/other/twapi/win/com.c:1972:20: note: initialize the variable 'pv2' to silence this warning
 1972 |     void       *pv2;
      |                    ^
      |                     = NULL
```

**Comment by apnadkarni** [comment]
There were a couple of bugs in twapi that I have fixed, including the ones your reported, bulk of the work has been getting the tests updated for various reasons like outdated certs, UI metrics etc. But 5.2 is not release ready, still work in progress.

With regards to packaging twapi for MSYS2, I'll try to be as objective as I can be :-)

Pros

- twapi is or has been fairly widely used for Tcl on Windows, by both commercial and govt outfits so there is considerable real world proof of robustness out there
- It is almost a necessity for writing full blown user applications. Without twapi, I am not aware of any other extension that will provide Windows services, COM, event logging, security and crypto API's, named pipes, authentication etc. among other things.

Cons

- twapi is more than a bit long in the tooth. The bulk of it was written two decades ago and in the past few years it has seen some bit rot as I have had extremely little time to spend on it. Part of 5.2 is to clean some of that up.
- There are some server-related components that are no longer tested, in particular related to domain users, Active Directory etc. I used to have access to the Platform SDK for setting up server VM's. I have not had that for a few years (not willing to spend $$ on MSDN for free code!) so testing for server related functions has suffered
- It should be possible to use the twapi Windows binaries that I provide with mingw64 built Tcl (I am not sure msys Tcl if there is difference) so folks wanting to use twapi would have that as an alternative; of course, not as convenient as being available through package manager.

Are you currently shipping Tcl 8.6 or Tcl 9?

**Comment by apnadkarni** [comment]
I've just released [5.2](https://github.com/apnadkarni/twapi/releases). Works for me, hope it works for you :-) The Windows binaries are built with gcc.

On a related note, what might be the hold up adding Tcl 9 to msys (in case you happen to know)? Can it co-exist with Tcl8 in the msys distribution or would it actually have to replace Tcl8?

I'm closing this bug on the assumption that the builds now work. If you are still having issues, please re-open.

**Comment by oscarfv** [comment]
TWAPI is now in the MSYS2 repository, for MINGW32, MINGW64, CLANG64 and UCRT64 environments.

Binaries still not published, they usually take a day or two.

**Comment by apnadkarni** [comment]
Great, will look for them.

Tcl 9 binary extensions will usually have a `tcl9` extension to distinguish from Tcl 8 binaries. tcl9registry14.dll versus tclreg13.dll for example. I don't know if that would make it easier for you to have both installed side by side.

In general, we are interested in hearing about such issues with co-installation. You are not the only packager with these :-)
